### ISSUE TITLE
ImportError: mac m1 arm64 processor

### ISSUE THREAD

**Issue by captchanjack** [urschrei/pypolyline#11]
Hello!

I can't seem to import the package on my mac m1 machine (arm64 processor)

```
>>> from pypolyline.cutil import encode_coordinates, decode_polyline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(~/venv/lib/python3.9/site-packages/pypolyline/cutil.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_decode_polyline_ffi'
```

Any ideas?

**Comment by urschrei** [comment]
Just to check, what version of `pypolyline` did you install, and was it from pypi?

**Comment by captchanjack** [comment]
Installed the latest version `0.2.74`

**Comment by urschrei** [comment]
Yep, looks like the wheel build is pulling in the `x86_64` dylib instead of the `aarch64` version. I'll have a look.

**Comment by urschrei** [comment]
`0.2.75` [is available on PyPI now](https://pypi.org/project/pypolyline/) (you might have to install with upgrade: `pip install pypolyline --upgrade` to get it), and it has the correct `arm64` library. Let me know if it works for you…

**Comment by captchanjack** [comment]
Perfect! Just tried and it works now.

Thanks!
