### ISSUE TITLE
Encodes a polyline with very close points, but raises DecodingError when decoding it

### ISSUE THREAD

**Issue by wxd** [urschrei/pypolyline#3]
I seem to have hit some kind of corner case (Python 3.7.7 on macOS):
```python

from pypolyline.util import encode_coordinates, decode_polyline

ps = [(51.7157979, -1.1944854), (51.715798, -1.1944871)]

encode_coordinates(ps, 5)  # b'wvszHphhF?>'

decode_polyline(encode_coordinates(ps, 6), 6)  # [[51.715798, -1.194485], [51.715798, -1.194487]]
decode_polyline(encode_coordinates(ps, 5), 5)  # pypolyline.util.DecodingError: Your Polyline was not valid and could not be decoded


# Rounding coordinates to 5 decimal digits
ps2 = [tuple(map(lambda coord: round(coord, 5), p)) for p in ps]  # [(51.7158, -1.19449), (51.7158, -1.19449)]

decode_polyline(encode_coordinates(ps2, 5), 5)  # [[51.7158, -1.19449], [51.7158, -1.19449]]
```

I'm not sure the fact that the points are very close to each other has anything to do with the error. [Google's Polyline Decoder](https://developers.google.com/maps/documentation/utilities/polylineutility) doesn't seem to have any decoding troubles.

**Comment by urschrei** [comment]
Hmmm this isn't causing an error for me, either on macOS (although 3.7.2) or CI. Are you running v0.2.2?

**Comment by wxd** [comment]
Sorry, forgot to include the package version. No, I'm on **v0.1.17**, which is what I get from `pip`:
```bash
$ pip install -U pypolyline
Requirement already up-to-date: pypolyline in ./.venv-airvi/lib/python3.7/site-packages (0.1.17)
Requirement already satisfied, skipping upgrade: numpy>=1.11.0 in ./.venv-airvi/lib/python3.7/site-packages (from pypolyline) (1.18.4)
```

I'll try to install **v0.2.2** from Github Releases later on this week and report the results.

Thank you for a quick reply!

**Comment by urschrei** [comment]
Sorry, v0.2.2 available on PyPI now.

**Comment by wxd** [comment]
...and the exception is gone. Thank you!
