### ISSUE TITLE
cutils.decode_polyline taking quite a long time to decode.

### ISSUE THREAD

**Issue by brad-4k** [urschrei/pypolyline#31]
Thank you for all of your hard work.

I'm evaluating different methods of decoding large polyline data and I found your project.

I've tried three things, thus far:  1. a hand written decoder, 2. polyline module, 3. pypolyline module.

In short, both the hand written decoder and the decoder provided by the polyline module return almost identical decoding times for each example.  (0.14s for the attached example)

!! **REVISED**
I re-ran the polyline.decode test and I'm getting roughly 0.04s to decode the same polyline data.

cutils.decode_polyline, however, produces times that are much longer. (4.65s for the attached example)

This was tested on two systems:
MacOS (x86), Python 3.9.12, pypolyline 0.2.78
AWS (x86), Python 3.9, pypolyline 0.2.78

Both produced very similar results.

Do you have any suggestions on increasing performance? (reducing the decode time)
[long_polyline.txt](https://github.com/urschrei/pypolyline/files/10944610/long_polyline.txt)

**Comment by urschrei** [comment]
Hi Brad, your comment was cut off.

**Comment by brad-4k** [comment]
Yes, sorry.  I accidentally triggered the <COMMENT> button.  I've updated the comment with the polyline attached as a text file.

**Comment by brad-4k** [comment]
BTW, the polyline data in the original post is from Valhalla, so it has a precision of _**6**_.

**Comment by urschrei** [comment]
> Processed 21502 points in 520 microseconds

Can you confirm that it was _microseconds_ (μs ) and not _milliseconds_ (ms)?

I've run a benchmark for the same number of coordinates on the `polyline` crate, and it decodes 21502 coordinates in around 620 ms with a precision of 6. That's 620,000 μs, or around 1000x slower than what you're saying the cpp version is doing.

**Comment by urschrei** [comment]
Using `pypolyline 0.3.0` (just released to PyPI) which incorporates a perf improvement I merged into the Rust library, I get an average decoding time of 2.69 ms for your test input, vs 1.57 s for the previous version. That's around a 600x speedup.

**Comment by brad-4k** [comment]
Stephan,  that fixed it!  Thank you!

Parsing time went from 4.4s to 0.005s.

Thank you for all your hard work!
