### ISSUE TITLE
Latitude error at position 0

### ISSUE THREAD

**Issue by ahmadshiddiqn** [urschrei/pypolyline#34]
Hello, sorry for the short issue. I tried using these coordinates:

```python
from pypolyline.cutil import encode_coordinates

coords = [
    [-6.944527, 107.580655], 
    [-6.944806, 107.581525], 
]

print(encode_coordinates(coords, 5))
```

it return

`b'Latitude error at position 0: 107.580655'`

is there something wrong with negative coordinates? or am i missing something?

Thanks!

**Comment by urschrei** [comment]
You are missing something. Please read the first line of the "Usage" section, and consider the minimum and maximum possible values of latitude.

**Comment by ahmadshiddiqn** [comment]
sorry, my bad. it supposed to be Longitude and Latitude not the other way around 😅 im so used to latitude, longitude!
