### ISSUE TITLE
Mac Python 3.8 support

### ISSUE THREAD

**Issue by bnaul** [urschrei/pypolyline#4]
Hi @urschrei, it looks like Python 3.8 wheels for Linux were uploaded to PyPI, but MacOS only goes up to 3.7. For some reason it also won't even fall back to installing from source:
```
(.venv) ➜  model git:(python_3_8) ✗ pip install pypolyline==0.2.2
ERROR: Could not find a version that satisfies the requirement pypolyline==0.2.2 (from versions: 0.1.4, 0.1.5, 0.1.7)
ERROR: No matching distribution found for pypolyline==0.2.2
```
Would it be possible to push 3.8 wheels for MacOS as well?

**Comment by urschrei** [comment]
v0.2.4 is available on PyPI now, with macOS wheels for Python 3.8. Sorry about that!

**Comment by bnaul** [comment]
thanks @urschrei !
