### ISSUE TITLE
Bug: first coordinates wrong

### ISSUE THREAD

**Issue by RenoFilla** [urschrei/pypolyline#8]
I run Python 3.7.11
The example on first page results in polyline b'ynh`IcftoCyq@Ne@ncBds@EEycB' rather than ynh`IcftoCyq@Ne@ncBds@EEycB

Inputting the resulting polyline into this https://developers.google.com/maps/documentation/utilities/polylineutility reveals that the first set is wrongly encoded.

**Comment by urschrei** [comment]
@RenoFilla Unless I'm misunderstanding you, the `b` prefix denotes a Python [byte](https://docs.python.org/3/library/stdtypes.html#bytes) string. If you need a UTF8-encoded string you can call [`decode()`](https://docs.python.org/3/library/stdtypes.html#bytes.decode) on it.

**Comment by RenoFilla** [comment]
> @RenoFilla Unless I'm misunderstanding you, the `b` prefix denotes a Python [byte](https://docs.python.org/3/library/stdtypes.html#bytes) string. If you need a UTF8-encoded string you can call [`decode()`](https://docs.python.org/3/library/stdtypes.html#bytes.decode) on it.
Haha, thanks, there I fired too fast. I should have stopped to look properly, first. You are right, of course. Sorry!
